### ISSUE TITLE
Wildcard * rendered as italics

### ISSUE THREAD

**Issue by jnthnwn** [quartz-scheduler/quartz-scheduler.github.io#2]
It appears that the section on the \* asterisk wildcard symbol got mistaken for markdown and leaves the text between two asterisks italicized.

`Wild-cards (the ‘*’ character) can be used to say “every” possible value of this field. Therefore the ‘*’ character...
`

is coming out as

Wild-cards (the ‘_’ character) can be used to say “every” possible value of this field. Therefore the ‘_’ character...

https://github.com/quartz-scheduler/quartz-scheduler.github.io/blob/master/documentation/quartz-2.2.x/tutorials/tutorial-lesson-06.html#L183

**Comment by zemian** [comment]
Fixed
